spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/easysign?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: abcd123!
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
